config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resource :favorites,only: [:create,:destroy]
   resources :book_comments,only: [:create,:destroy]
 end

  resources :users, only: [:index,:show,:edit,:update] do
   resource :relationships,only: [:create,:destroy]
   get :followings, on: :member
   get :followers, on: :member
   #あるユーザーがフォローする人全員を表示するルーティング
   #あるユーザーをフォローしてくれている人全員を表示するルーティング(つまりフォロワー)
   #on: :menberと書く事で、ルーティングにidを持たせることができる
 end
  
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  has_one_attached :image
  
  # 引数で渡されたユーザーidがFavoriteテーブル内に存在(exsits?)しているか
  def favorited_by?(user)
    favorites.exists?(user_id:user.id)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_book, only: [:update,:edit]

  def show
    @book = Book.new
    @book_id = Book.find(params[:id])
    @user = @book_id.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @user = User.find(current_user.id)
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = User.find(current_user.id)
    @books = Book.all
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
  
   def ensure_correct_book
     @book = Book.find(params[:id])
     @user = @book.user
   if
      @user != current_user
      redirect_to books_path
   end
   end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th colspan = "3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td nowrap><%= book.body %></td>
        <td>
          <% if book.favorited_by?(current_user)%>
          <%= link_to book_favorites_path(book.id), method: :delete do %>
          ♥<%= book.favorites.count %>
          <% end %>
          <% else %>
          <%= link_to book_favorites_path(book.id), method: :post do %>
          ♡<%= book.favorites.count %>
          <% end %>
          <% end %></td>
         <td nowrap>コメント数:<%= book.book_comments.count %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  		<% end %>
  		</div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= form_with model:@book, local:true do |f| %>
  <%= render 'layouts/errors', obj: @book %>
  <%end%>
  
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
     
      </div>
      
      <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' ,user: @user %>
      <h2 class="mt-3">New book</h2>
      
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to book_path(@book_id) do %>
            <%= image_tag @user.get_profile_image(100,100) %><br>
            <% end %>
            <%= link_to @user.name,user_path(@user) %><%#= @user.name %>
          </td>
          <td><%= link_to @book_id.title,book_path(@book_id) %></td><%#= link_to book_path,@book.title %>
          <td><%= @book_id.body %></td><%#= @book.body %>
          
          <!--イイねボタン-->
          <td><% if @book_id.favorited_by?(current_user)%>
               <%= link_to book_favorites_path(@book_id), method: :delete do %>
              ♥<%= @book_id.favorites.count %>
               <% end %>
              <% else %>
               <%= link_to book_favorites_path(@book_id), method: :post do %>
              ♡<%= @book_id.favorites.count %>
               <% end %>
              <% end %>
          </td>
          
          <!--コメント数表示-->
          <td nowrap>コメント数<%= @book_id.book_comments.count %></td>
          
          <% if @book_id.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path, class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book_id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      
      <!--コメント機能表示・投稿-->
      <table class='table'>
        <tr>
          <td>
            <div>
              <% @book_id.book_comments.each do |book_comment| %> <!--コメントを一覧にするeachメソッドを定義-->
              <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p><!--コメント投稿者の登録画像-->
              <%= link_to @user.name,user_path(@user) %> <!--コメント投稿者の名前とマイページへのリンク-->
              <%= book_comment.comment %><!--投稿者のコメント内容表示-->
              <% if @book_id.user == current_user %>
              <%= link_to 'Destroy', book_book_comment_path(book_comment.book,book_comment), method: :delete, class: "btn btn-sm btn-danger destroy_book_#{book_comment}"%><!--コメントの削除-->
              <% end %>
              <% end %>
            </div>
           </td>
         </tr>
      </table>
        <div>
          <%= render 'layouts/errors', obj: @book_comment %>
          <%= form_with model: [@book_id, @book_comment] do |f| %> <!-- コメント投稿用のメソッド、@bookと@book_comment2つ？-->
          <%= f.text_area :comment,size: "70x5" %><br>
          <%= f.submit "送信" %>
          <% end %>
        </div>
    </div>
  </div>
</div>